"""Added Lesson Plan

Revision ID: 0db32387d4d7
Revises: 521ae925ffbb
Create Date: 2025-12-13 03:44:46.465824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0db32387d4d7'
down_revision = '521ae925ffbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teaching_plan',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('unit_number', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=255), nullable=False),
    sa.Column('planned_hours', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['staff_profile.staff_id'], name=op.f('fk_teaching_plan_created_by_id_staff_profile')),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.subject_id'], name=op.f('fk_teaching_plan_subject_id_subject')),
    sa.PrimaryKeyConstraint('plan_id', name=op.f('pk_teaching_plan'))
    )
    op.create_table('lesson_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('completion_percentage', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['teaching_plan.plan_id'], name=op.f('fk_lesson_log_plan_id_teaching_plan')),
    sa.ForeignKeyConstraint(['session_id'], ['session_log.session_id'], name=op.f('fk_lesson_log_session_id_session_log')),
    sa.PrimaryKeyConstraint('log_id', name=op.f('pk_lesson_log'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_log')
    op.drop_table('teaching_plan')
    # ### end Alembic commands ###
