"""Added Term Grant

Revision ID: 2810ff2bca74
Revises: 0d53ff8a9829
Create Date: 2025-12-12 03:18:16.155803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2810ff2bca74'
down_revision = '0d53ff8a9829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('term_grant_record',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('attendance_perc', sa.Float(), nullable=True),
    sa.Column('avg_ca_score', sa.Float(), nullable=True),
    sa.Column('failed_subjects_count', sa.Integer(), nullable=True),
    sa.Column('active_detentions', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['class_section.section_id'], name=op.f('fk_term_grant_record_section_id_class_section')),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.student_id'], name=op.f('fk_term_grant_record_student_id_student_profile')),
    sa.PrimaryKeyConstraint('record_id', name=op.f('pk_term_grant_record'))
    )
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_department_hod_staff_id_staff_profile'), 'staff_profile', ['hod_staff_id'], ['staff_id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_department_hod_staff_id_staff_profile'), type_='foreignkey')

    op.drop_table('term_grant_record')
    # ### end Alembic commands ###
