"""Add must_change_password column

Revision ID: 2f64c4bd5778
Revises: f582326554e5
Create Date: 2025-12-23 20:27:26.227282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f64c4bd5778'
down_revision = 'f582326554e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archived_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_name', sa.String(length=50), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('subject_code', sa.String(length=20), nullable=True),
    sa.Column('subject_name', sa.String(length=100), nullable=True),
    sa.Column('teacher_name', sa.String(length=100), nullable=True),
    sa.Column('archived_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_archived_allocation'))
    )
    op.create_table('archived_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_name', sa.String(length=50), nullable=True),
    sa.Column('section_name', sa.String(length=50), nullable=True),
    sa.Column('day', sa.String(length=20), nullable=True),
    sa.Column('time_slot', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('teacher', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_archived_schedule'))
    )
    op.create_table('department',
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hod_staff_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['hod_staff_id'], ['staff_profile.staff_id'], name=op.f('fk_department_hod_staff_id_staff_profile'), use_alter=True),
    sa.PrimaryKeyConstraint('dept_id', name=op.f('pk_department')),
    sa.UniqueConstraint('name', name=op.f('uq_department_name'))
    )
    op.create_table('feedback_cycle',
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('cycle_id', name=op.f('pk_feedback_cycle'))
    )
    op.create_table('feedback_question',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('question_id', name=op.f('pk_feedback_question'))
    )
    op.create_table('system_config',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_config'))
    )
    op.create_table('system_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('performed_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('log_id', name=op.f('pk_system_log'))
    )
    op.create_table('user_master',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('two_factor_secret', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_master')),
    sa.UniqueConstraint('username', name=op.f('uq_user_master_username'))
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_master.user_id'], name=op.f('fk_notification_user_id_user_master')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    op.create_table('parent_profile',
    sa.Column('parent_id', sa.String(length=36), nullable=False),
    sa.Column('father_name', sa.String(length=100), nullable=True),
    sa.Column('mother_name', sa.String(length=100), nullable=True),
    sa.Column('primary_phone', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['user_master.user_id'], name=op.f('fk_parent_profile_parent_id_user_master')),
    sa.PrimaryKeyConstraint('parent_id', name=op.f('pk_parent_profile')),
    sa.UniqueConstraint('primary_phone', name=op.f('uq_parent_profile_primary_phone'))
    )
    op.create_table('push_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('fcm_token', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_master.user_id'], name=op.f('fk_push_device_user_id_user_master')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_device')),
    sa.UniqueConstraint('platform', 'device_id', 'user_id', name='uq_push_device_platform_device_user')
    )
    with op.batch_alter_table('push_device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_device_fcm_token'), ['fcm_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_device_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_master.user_id'], name=op.f('fk_refresh_token_user_id_user_master')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token'))
    )
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_token_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_token_user_id'), ['user_id'], unique=False)

    op.create_table('room_master',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=False),
    sa.Column('room_type', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['department.dept_id'], name=op.f('fk_room_master_dept_id_department')),
    sa.PrimaryKeyConstraint('room_id', name=op.f('pk_room_master')),
    sa.UniqueConstraint('room_number', name=op.f('uq_room_master_room_number'))
    )
    op.create_table('staff_profile',
    sa.Column('staff_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('email_contact', sa.String(length=100), nullable=True),
    sa.Column('primary_department_id', sa.Integer(), nullable=True),
    sa.Column('designation', sa.String(length=50), nullable=True),
    sa.Column('is_event_coordinator', sa.Boolean(), nullable=True),
    sa.Column('is_amc_member', sa.Boolean(), nullable=True),
    sa.Column('is_amc_head', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['primary_department_id'], ['department.dept_id'], name=op.f('fk_staff_profile_primary_department_id_department')),
    sa.ForeignKeyConstraint(['staff_id'], ['user_master.user_id'], name=op.f('fk_staff_profile_staff_id_user_master')),
    sa.PrimaryKeyConstraint('staff_id', name=op.f('pk_staff_profile')),
    sa.UniqueConstraint('employee_code', name=op.f('uq_staff_profile_employee_code'))
    )
    op.create_table('subject',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('subject_type', sa.String(length=50), nullable=True),
    sa.Column('l_count', sa.Integer(), nullable=True),
    sa.Column('t_count', sa.Integer(), nullable=True),
    sa.Column('p_count', sa.Integer(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('target_class', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['department.dept_id'], name=op.f('fk_subject_dept_id_department')),
    sa.PrimaryKeyConstraint('subject_id', name=op.f('pk_subject')),
    sa.UniqueConstraint('code', name=op.f('uq_subject_code'))
    )
    op.create_table('class_section',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('class_level', sa.String(length=50), nullable=False),
    sa.Column('class_teacher_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['class_teacher_id'], ['staff_profile.staff_id'], name=op.f('fk_class_section_class_teacher_id_staff_profile')),
    sa.PrimaryKeyConstraint('section_id', name=op.f('pk_class_section'))
    )
    op.create_table('event_master',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('coordinator_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['coordinator_id'], ['staff_profile.staff_id'], name=op.f('fk_event_master_coordinator_id_staff_profile')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_event_master'))
    )
    op.create_table('teaching_plan',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('unit_number', sa.Integer(), nullable=False),
    sa.Column('sub_unit', sa.String(length=50), nullable=True),
    sa.Column('topic_name', sa.String(length=255), nullable=False),
    sa.Column('planned_hours', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['staff_profile.staff_id'], name=op.f('fk_teaching_plan_created_by_id_staff_profile')),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.subject_id'], name=op.f('fk_teaching_plan_subject_id_subject')),
    sa.PrimaryKeyConstraint('plan_id', name=op.f('pk_teaching_plan'))
    )
    op.create_table('elective_window',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('target_semester_no', sa.Integer(), nullable=False),
    sa.Column('bucket', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('min_batch_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['class_section.section_id'], name=op.f('fk_elective_window_section_id_class_section')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_elective_window'))
    )
    op.create_table('feedback_response',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['feedback_cycle.cycle_id'], name=op.f('fk_feedback_response_cycle_id_feedback_cycle')),
    sa.ForeignKeyConstraint(['question_id'], ['feedback_question.question_id'], name=op.f('fk_feedback_response_question_id_feedback_question')),
    sa.ForeignKeyConstraint(['section_id'], ['class_section.section_id'], name=op.f('fk_feedback_response_section_id_class_section')),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.subject_id'], name=op.f('fk_feedback_response_subject_id_subject')),
    sa.ForeignKeyConstraint(['teacher_id'], ['staff_profile.staff_id'], name=op.f('fk_feedback_response_teacher_id_staff_profile')),
    sa.PrimaryKeyConstraint('response_id', name=op.f('pk_feedback_response'))
    )
    op.create_table('mentor_batch',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('batch_name', sa.String(length=50), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['mentor_id'], ['staff_profile.staff_id'], name=op.f('fk_mentor_batch_mentor_id_staff_profile')),
    sa.ForeignKeyConstraint(['section_id'], ['class_section.section_id'], name=op.f('fk_mentor_batch_section_id_class_section')),
    sa.PrimaryKeyConstraint('batch_id', name=op.f('pk_mentor_batch'))
    )
    op.create_table('semester_course_structure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('semester_no', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['class_section.section_id'], name=op.f('fk_semester_course_structure_section_id_class_section')),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.subject_id'], name=op.f('fk_semester_course_structure_subject_id_subject')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semester_course_structure'))
    )
    op.create_table('subject_allocation',
    sa.Column('allocation_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['class_section.section_id'], name=op.f('fk_subject_allocation_section_id_class_section')),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.subject_id'], name=op.f('fk_subject_allocation_subject_id_subject')),
    sa.ForeignKeyConstraint(['teacher_id'], ['staff_profile.staff_id'], name=op.f('fk_subject_allocation_teacher_id_staff_profile')),
    sa.PrimaryKeyConstraint('allocation_id', name=op.f('pk_subject_allocation'))
    )
    op.create_table('weekly_schedule',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.String(length=36), nullable=True),
    sa.Column('day_of_week', sa.String(length=15), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('session_type', sa.String(length=20), nullable=True),
    sa.Column('target_batch', sa.String(length=20), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room_master.room_id'], name=op.f('fk_weekly_schedule_room_id_room_master')),
    sa.ForeignKeyConstraint(['section_id'], ['class_section.section_id'], name=op.f('fk_weekly_schedule_section_id_class_section')),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.subject_id'], name=op.f('fk_weekly_schedule_subject_id_subject')),
    sa.ForeignKeyConstraint(['teacher_id'], ['staff_profile.staff_id'], name=op.f('fk_weekly_schedule_teacher_id_staff_profile')),
    sa.PrimaryKeyConstraint('schedule_id', name=op.f('pk_weekly_schedule'))
    )
    op.create_table('elective_offering',
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('window_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['class_section.section_id'], name=op.f('fk_elective_offering_section_id_class_section')),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.subject_id'], name=op.f('fk_elective_offering_subject_id_subject')),
    sa.ForeignKeyConstraint(['window_id'], ['elective_window.id'], name=op.f('fk_elective_offering_window_id_elective_window')),
    sa.PrimaryKeyConstraint('offering_id', name=op.f('pk_elective_offering'))
    )
    op.create_table('load_adjustment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.String(length=36), nullable=False),
    sa.Column('adjuster_id', sa.String(length=36), nullable=False),
    sa.Column('req_date', sa.Date(), nullable=False),
    sa.Column('req_schedule_id', sa.Integer(), nullable=False),
    sa.Column('adj_date', sa.Date(), nullable=False),
    sa.Column('adj_schedule_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['adj_schedule_id'], ['weekly_schedule.schedule_id'], name=op.f('fk_load_adjustment_adj_schedule_id_weekly_schedule')),
    sa.ForeignKeyConstraint(['adjuster_id'], ['staff_profile.staff_id'], name=op.f('fk_load_adjustment_adjuster_id_staff_profile')),
    sa.ForeignKeyConstraint(['req_schedule_id'], ['weekly_schedule.schedule_id'], name=op.f('fk_load_adjustment_req_schedule_id_weekly_schedule')),
    sa.ForeignKeyConstraint(['requester_id'], ['staff_profile.staff_id'], name=op.f('fk_load_adjustment_requester_id_staff_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_load_adjustment'))
    )
    op.create_table('mentor_meeting',
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('agenda', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['mentor_batch.batch_id'], name=op.f('fk_mentor_meeting_batch_id_mentor_batch')),
    sa.ForeignKeyConstraint(['mentor_id'], ['staff_profile.staff_id'], name=op.f('fk_mentor_meeting_mentor_id_staff_profile')),
    sa.PrimaryKeyConstraint('meeting_id', name=op.f('pk_mentor_meeting'))
    )
    op.create_table('session_log',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('actual_teacher_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['actual_teacher_id'], ['staff_profile.staff_id'], name=op.f('fk_session_log_actual_teacher_id_staff_profile')),
    sa.ForeignKeyConstraint(['schedule_id'], ['weekly_schedule.schedule_id'], name=op.f('fk_session_log_schedule_id_weekly_schedule')),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_session_log'))
    )
    op.create_table('student_profile',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('admission_number', sa.String(length=50), nullable=False),
    sa.Column('parent_user_id', sa.String(length=36), nullable=True),
    sa.Column('current_section_id', sa.Integer(), nullable=True),
    sa.Column('academic_status', sa.String(length=50), nullable=True),
    sa.Column('batch', sa.String(length=20), nullable=True),
    sa.Column('mentor_batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_section_id'], ['class_section.section_id'], name=op.f('fk_student_profile_current_section_id_class_section')),
    sa.ForeignKeyConstraint(['mentor_batch_id'], ['mentor_batch.batch_id'], name=op.f('fk_student_profile_mentor_batch_id_mentor_batch')),
    sa.ForeignKeyConstraint(['parent_user_id'], ['parent_profile.parent_id'], name=op.f('fk_student_profile_parent_user_id_parent_profile')),
    sa.ForeignKeyConstraint(['student_id'], ['user_master.user_id'], name=op.f('fk_student_profile_student_id_user_master')),
    sa.PrimaryKeyConstraint('student_id', name=op.f('pk_student_profile')),
    sa.UniqueConstraint('admission_number', name=op.f('uq_student_profile_admission_number'))
    )
    op.create_table('attendance_transaction',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session_log.session_id'], name=op.f('fk_attendance_transaction_session_id_session_log')),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.student_id'], name=op.f('fk_attendance_transaction_student_id_student_profile')),
    sa.PrimaryKeyConstraint('transaction_id', name=op.f('pk_attendance_transaction'))
    )
    op.create_table('ca_marks',
    sa.Column('mark_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('ta1', sa.Float(), nullable=True),
    sa.Column('ta2', sa.Float(), nullable=True),
    sa.Column('ta3', sa.Float(), nullable=True),
    sa.Column('a1', sa.Float(), nullable=True),
    sa.Column('a2', sa.Float(), nullable=True),
    sa.Column('a3', sa.Float(), nullable=True),
    sa.Column('a4', sa.Float(), nullable=True),
    sa.Column('a5', sa.Float(), nullable=True),
    sa.Column('learner_status', sa.String(length=20), nullable=True),
    sa.Column('attendance_score', sa.Float(), nullable=True),
    sa.Column('total_ca', sa.Float(), nullable=True),
    sa.Column('is_published_ta1', sa.Boolean(), nullable=True),
    sa.Column('is_published_ta2', sa.Boolean(), nullable=True),
    sa.Column('is_published_ta3', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['class_section.section_id'], name=op.f('fk_ca_marks_section_id_class_section')),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.student_id'], name=op.f('fk_ca_marks_student_id_student_profile')),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.subject_id'], name=op.f('fk_ca_marks_subject_id_subject')),
    sa.PrimaryKeyConstraint('mark_id', name=op.f('pk_ca_marks'))
    )
    op.create_table('detention_record',
    sa.Column('detention_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_by_staff_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('assignment_details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('submission_doc_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_staff_id'], ['staff_profile.staff_id'], name=op.f('fk_detention_record_assigned_by_staff_id_staff_profile')),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.student_id'], name=op.f('fk_detention_record_student_id_student_profile')),
    sa.PrimaryKeyConstraint('detention_id', name=op.f('pk_detention_record'))
    )
    op.create_table('event_participation',
    sa.Column('participation_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('student_role', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event_master.event_id'], name=op.f('fk_event_participation_event_id_event_master')),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.student_id'], name=op.f('fk_event_participation_student_id_student_profile')),
    sa.PrimaryKeyConstraint('participation_id', name=op.f('pk_event_participation'))
    )
    op.create_table('leave_application',
    sa.Column('leave_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('total_days', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('leave_type', sa.String(length=50), nullable=True),
    sa.Column('document_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.student_id'], name=op.f('fk_leave_application_student_id_student_profile')),
    sa.PrimaryKeyConstraint('leave_id', name=op.f('pk_leave_application'))
    )
    op.create_table('lesson_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('completion_percentage', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['teaching_plan.plan_id'], name=op.f('fk_lesson_log_plan_id_teaching_plan')),
    sa.ForeignKeyConstraint(['session_id'], ['session_log.session_id'], name=op.f('fk_lesson_log_session_id_session_log')),
    sa.PrimaryKeyConstraint('log_id', name=op.f('pk_lesson_log'))
    )
    op.create_table('mentor_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('mentor_id', sa.String(length=36), nullable=False),
    sa.Column('mentor_batch_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('issue_category', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['mentor_batch_id'], ['mentor_batch.batch_id'], name=op.f('fk_mentor_log_mentor_batch_id_mentor_batch')),
    sa.ForeignKeyConstraint(['mentor_id'], ['staff_profile.staff_id'], name=op.f('fk_mentor_log_mentor_id_staff_profile')),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.student_id'], name=op.f('fk_mentor_log_student_id_student_profile')),
    sa.PrimaryKeyConstraint('log_id', name=op.f('pk_mentor_log'))
    )
    op.create_table('student_elective',
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('window_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.student_id'], name=op.f('fk_student_elective_student_id_student_profile')),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.subject_id'], name=op.f('fk_student_elective_subject_id_subject')),
    sa.ForeignKeyConstraint(['window_id'], ['elective_window.id'], name=op.f('fk_student_elective_window_id_elective_window')),
    sa.PrimaryKeyConstraint('map_id', name=op.f('pk_student_elective'))
    )
    op.create_table('student_feedback_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('submitted_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['feedback_cycle.cycle_id'], name=op.f('fk_student_feedback_status_cycle_id_feedback_cycle')),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.student_id'], name=op.f('fk_student_feedback_status_student_id_student_profile')),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.subject_id'], name=op.f('fk_student_feedback_status_subject_id_subject')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_feedback_status'))
    )
    op.create_table('term_grant_record',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('attendance_perc', sa.Float(), nullable=True),
    sa.Column('avg_ca_score', sa.Float(), nullable=True),
    sa.Column('failed_subjects_count', sa.Integer(), nullable=True),
    sa.Column('active_detentions', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['class_section.section_id'], name=op.f('fk_term_grant_record_section_id_class_section')),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.student_id'], name=op.f('fk_term_grant_record_student_id_student_profile')),
    sa.PrimaryKeyConstraint('record_id', name=op.f('pk_term_grant_record'))
    )
    op.create_table('leave_workflow_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('leave_id', sa.Integer(), nullable=False),
    sa.Column('action_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['action_by_user_id'], ['user_master.user_id'], name=op.f('fk_leave_workflow_log_action_by_user_id_user_master')),
    sa.ForeignKeyConstraint(['leave_id'], ['leave_application.leave_id'], name=op.f('fk_leave_workflow_log_leave_id_leave_application')),
    sa.PrimaryKeyConstraint('log_id', name=op.f('pk_leave_workflow_log'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leave_workflow_log')
    op.drop_table('term_grant_record')
    op.drop_table('student_feedback_status')
    op.drop_table('student_elective')
    op.drop_table('mentor_log')
    op.drop_table('lesson_log')
    op.drop_table('leave_application')
    op.drop_table('event_participation')
    op.drop_table('detention_record')
    op.drop_table('ca_marks')
    op.drop_table('attendance_transaction')
    op.drop_table('student_profile')
    op.drop_table('session_log')
    op.drop_table('mentor_meeting')
    op.drop_table('load_adjustment')
    op.drop_table('elective_offering')
    op.drop_table('weekly_schedule')
    op.drop_table('subject_allocation')
    op.drop_table('semester_course_structure')
    op.drop_table('mentor_batch')
    op.drop_table('feedback_response')
    op.drop_table('elective_window')
    op.drop_table('teaching_plan')
    op.drop_table('event_master')
    op.drop_table('class_section')
    op.drop_table('subject')
    op.drop_table('staff_profile')
    op.drop_table('room_master')
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_token_token_hash'))

    op.drop_table('refresh_token')
    with op.batch_alter_table('push_device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_device_user_id'))
        batch_op.drop_index(batch_op.f('ix_push_device_fcm_token'))

    op.drop_table('push_device')
    op.drop_table('parent_profile')
    op.drop_table('notification')
    op.drop_table('user_master')
    op.drop_table('system_log')
    op.drop_table('system_config')
    op.drop_table('feedback_question')
    op.drop_table('feedback_cycle')
    op.drop_table('department')
    op.drop_table('archived_schedule')
    op.drop_table('archived_allocation')
    # ### end Alembic commands ###
