"""add mobile auth tokens and push devices

Revision ID: 43ab2468c823
Revises: c7b1c3e8a9f1
Create Date: 2025-12-14 14:57:56.398545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ab2468c823'
down_revision = 'c7b1c3e8a9f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('fcm_token', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_master.user_id'], name=op.f('fk_push_device_user_id_user_master')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_device')),
    sa.UniqueConstraint('platform', 'device_id', 'user_id', name='uq_push_device_platform_device_user')
    )
    with op.batch_alter_table('push_device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_device_fcm_token'), ['fcm_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_device_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_master.user_id'], name=op.f('fk_refresh_token_user_id_user_master')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token'))
    )
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_token_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_token_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_token_token_hash'))

    op.drop_table('refresh_token')
    with op.batch_alter_table('push_device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_device_user_id'))
        batch_op.drop_index(batch_op.f('ix_push_device_fcm_token'))

    op.drop_table('push_device')
    # ### end Alembic commands ###
