"""Added Feedback Module

Revision ID: 521ae925ffbb
Revises: 2810ff2bca74
Create Date: 2025-12-12 13:22:39.771080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '521ae925ffbb'
down_revision = '2810ff2bca74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_cycle',
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('cycle_id', name=op.f('pk_feedback_cycle'))
    )
    op.create_table('feedback_question',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('question_id', name=op.f('pk_feedback_question'))
    )
    op.create_table('feedback_response',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['feedback_cycle.cycle_id'], name=op.f('fk_feedback_response_cycle_id_feedback_cycle')),
    sa.ForeignKeyConstraint(['question_id'], ['feedback_question.question_id'], name=op.f('fk_feedback_response_question_id_feedback_question')),
    sa.ForeignKeyConstraint(['section_id'], ['class_section.section_id'], name=op.f('fk_feedback_response_section_id_class_section')),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.subject_id'], name=op.f('fk_feedback_response_subject_id_subject')),
    sa.ForeignKeyConstraint(['teacher_id'], ['staff_profile.staff_id'], name=op.f('fk_feedback_response_teacher_id_staff_profile')),
    sa.PrimaryKeyConstraint('response_id', name=op.f('pk_feedback_response'))
    )
    op.create_table('student_feedback_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('submitted_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['feedback_cycle.cycle_id'], name=op.f('fk_student_feedback_status_cycle_id_feedback_cycle')),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.student_id'], name=op.f('fk_student_feedback_status_student_id_student_profile')),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.subject_id'], name=op.f('fk_student_feedback_status_subject_id_subject')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_feedback_status'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_feedback_status')
    op.drop_table('feedback_response')
    op.drop_table('feedback_question')
    op.drop_table('feedback_cycle')
    # ### end Alembic commands ###
