"""Added Archive Tables

Revision ID: aba0eb65ab1f
Revises: e3a2507186a6
Create Date: 2025-12-14 01:59:54.618985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba0eb65ab1f'
down_revision = 'e3a2507186a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archived_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_name', sa.String(length=50), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('subject_code', sa.String(length=20), nullable=True),
    sa.Column('subject_name', sa.String(length=100), nullable=True),
    sa.Column('teacher_name', sa.String(length=100), nullable=True),
    sa.Column('archived_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_archived_allocation'))
    )
    op.create_table('archived_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_name', sa.String(length=50), nullable=True),
    sa.Column('section_name', sa.String(length=50), nullable=True),
    sa.Column('day', sa.String(length=20), nullable=True),
    sa.Column('time_slot', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('teacher', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_archived_schedule'))
    )
    op.create_table('system_config',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_config'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_config')
    op.drop_table('archived_schedule')
    op.drop_table('archived_allocation')
    # ### end Alembic commands ###
