"""Add must_change_password column

Revision ID: cf8f089488d4
Revises: 43ab2468c823
Create Date: 2025-12-23 19:39:34.930567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf8f089488d4'
down_revision = '43ab2468c823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Removed auto-generated FK constraint for department table 
    # that was already created in an earlier migration
    
    with op.batch_alter_table('user_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_master', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')

    # Note: Removed auto-generated FK constraint drop for department table
    # that should not be dropped here as it's managed by an earlier migration

    # ### end Alembic commands ###
