"""Added Load Adjustment

Revision ID: e3a2507186a6
Revises: f5c8dff9c799
Create Date: 2025-12-13 14:00:34.757664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a2507186a6'
down_revision = 'f5c8dff9c799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('load_adjustment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.String(length=36), nullable=False),
    sa.Column('adjuster_id', sa.String(length=36), nullable=False),
    sa.Column('req_date', sa.Date(), nullable=False),
    sa.Column('req_schedule_id', sa.Integer(), nullable=False),
    sa.Column('adj_date', sa.Date(), nullable=False),
    sa.Column('adj_schedule_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['adj_schedule_id'], ['weekly_schedule.schedule_id'], name=op.f('fk_load_adjustment_adj_schedule_id_weekly_schedule')),
    sa.ForeignKeyConstraint(['adjuster_id'], ['staff_profile.staff_id'], name=op.f('fk_load_adjustment_adjuster_id_staff_profile')),
    sa.ForeignKeyConstraint(['req_schedule_id'], ['weekly_schedule.schedule_id'], name=op.f('fk_load_adjustment_req_schedule_id_weekly_schedule')),
    sa.ForeignKeyConstraint(['requester_id'], ['staff_profile.staff_id'], name=op.f('fk_load_adjustment_requester_id_staff_profile')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_load_adjustment'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('load_adjustment')
    # ### end Alembic commands ###
