"""Add must_change_password column

Revision ID: f582326554e5
Revises: cf8f089488d4
Create Date: 2025-12-23 19:41:09.975954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f582326554e5'
down_revision = 'cf8f089488d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_department_hod_staff_id_staff_profile'), 'staff_profile', ['hod_staff_id'], ['staff_id'], use_alter=True)

    with op.batch_alter_table('user_master', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_master', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')

    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_department_hod_staff_id_staff_profile'), type_='foreignkey')

    # ### end Alembic commands ###
