"""Added sub unit to Lesson Plan

Revision ID: f5c8dff9c799
Revises: 0db32387d4d7
Create Date: 2025-12-13 04:07:13.826893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5c8dff9c799'
down_revision = '0db32387d4d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teaching_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_unit', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teaching_plan', schema=None) as batch_op:
        batch_op.drop_column('sub_unit')

    # ### end Alembic commands ###
